SciCatProject/scicatlive

seed_db/mongo_import.sh
seed_db/seed/Dataset.json
seed_db/seed/Instrument.json
seed_db/seed/OrigDatablock.json
seed_db/seed/Proposal.json
seed_db/seed/PublishedData.json
seed_db/seed/Sample.json

OrigDatablock added and data format reviewed

Add origdatablock and review sample data

---

seed_db/seed/Dataset.json
seed_db/seed/Instrument.json
seed_db/seed/Proposal.json
seed_db/seed/Sample.json

Keys used in datasets did not comply with the ones expected by catanie. This PR should fix this issue

Amend datasets to fix fe issues

---

docker-compose.yaml

Adding version: '3' to docker-compose.yaml solves the issue

---

README.md
config/frontend/config.json
docker-compose.yaml

Use traefik subdomains for clarity

---

docker-compose.yaml
seed_db/init.js
seed_db/mongo_import.sh

Mongo 7.0 upgrade

---

config/proxy/docker-compose.yaml
docker-compose.yaml

Move traefik to own module

---

config/searchapi/README.md
config/searchapi/config/.env
config/searchapi/docker-compose.yaml
docker-compose.yaml

Move searchapi to own module

---

config/backend/docker-compose.yaml
config/frontend/docker-compose.yaml
docker-compose.yaml

Adds health check to scicat be in order to avoid any potential issues with services that depend on it (mainly archive mock)

add health check to backend

---

config/archivemock/config/.env
config/archivemock/docker-compose.yaml
docker-compose.yaml

Move archivalmock to own module

---

config/rabbitmq/docker-compose.yaml
docker-compose.yaml

Move rabbitmq to own module

---

README.md
config/backend/README.md

Add local accounts to readme and reference in main

---

services/archivemock/README.md

Adds a README for the Archive Mock container

add archive mock README.md

---

README.md

Explain
* how to add a new one
* how to select which one to run
should close: #80

Rewrite readme to point to each service

---

services/frontend/docker-compose.yaml

Update frontend container to latest stable

---

services/backend/docker-compose.yaml

Use be container from ghcr

---

services/frontend/docker-compose.yaml

Use fe container from ghcr

---

.github/renovate.json

* Add renovate.json
* move renovate.json to .github folder
* closes #44 
---------

Configure Renovate (#1)

---

.env

Set default BE_VERSION to backend

---

README.md
services/frontend/README.md
services/frontend/config/config.base.json
services/frontend/config/config.v3.json
services/frontend/config/init.sh
services/frontend/docker-compose.yaml

Allow FE to merge json files alphabetically

---

.github/workflows/docker_compose_test.yaml
README.md
docker-compose.yaml
services/backend/README.md
services/backendnext/docker-compose.yaml
services/frontend/config/config.base.json
services/frontend/config/config.v3.json

relates to #107 and #115 
will have conflicts with #123

Allow only one backend at a time

---

.github/eslint.config.mjs
.github/workflows/docker_compose_test.yaml
.gitignore
services/frontend/config/init.sh
services/mongodb/config/init.js

Closes #122 
* Adds linting for shell scripts, json and javascript files.
* Fixes fe's init.sh in accordance with shellcheck (with two careful exceptions)

Add sh json javascript linting

---

.github/workflows/docker_compose_test.yaml

Rename master to main

---

services/proxy/compose.yaml

v3 seems to be officially released now

Upgrade traefik to v3

---

services/backend/services/v4/compose.base.yaml

the tag is not required anymore after #167

Remove platform tag

---

services/backend/services/keycloak/.compose.yaml

Remove leftover kc file

---

.github/workflows/compose_test.yaml

Avoid readme changes to run CI

---

services/backend/services/v3/compose.jobs.yaml
services/backend/services/v3/compose.oidc.yaml

This should fix the issues during the demo

Add config js env variables in v3

---

.github/mkdocs.yaml
.github/mkdocs_relative_to.py
.github/workflows/compose_test.yaml
.github/workflows/mkdocs.yaml
README.md
services/backend/README.md
services/mongodb/README.md

Add mkdocs pipeline for nested readmes

---

services/backend/services/v3/config/config.local.js

Fix an issue related to the job mocking, where the backend would not end up being configured correctly to post jobs to rabbitmq.

fix job mock

---

.github/mkdocs/mkdocs.yaml
.github/mkdocs/relative_to.py
.github/workflows/mkdocs.yaml

Add github link in docs

---

.github/changed_files.yaml
.github/workflows/compose_test.yaml
README.md

This PRs groups changed files depending on context, making it easier for future changes, and simplifies the IFs. It will also be useful for a near PR where I'd like to trigger the doc "linting" which will be triggered by .md changes and check if the links work fine

Group changed files depending on config

---

.github/changed_files.yaml
.github/mkdocs/relative_to.py
.github/workflows/compose_test.yaml
README.md
services/backend/services/v3/README.md
services/backend/services/v4/README.md
services/mongodb/README.md

This job checks the documentation links, internal and external and exists if any is not 20x
closes: #230

Add job to check .mds links

---

.github/changed_files.yaml
.github/mkdocs/relative_to.py
.github/workflows/compose_test.yaml
.gitignore

Add python lint with ruff

---

.github/changed_files.yaml
.github/mkdocs/overrides/main.html
.github/workflows/compose_test.yaml

Add linting step for html files

---

.github/actions/mkdocs-pages/action.yaml
.github/changed_files.yaml
.github/workflows/compose_test.yaml
.github/workflows/mkdocs.yaml

Move mkdocs to an action for reusability

---

README.md

Change readme https to http

---

.github/actions/mkdocs-pages/action.yaml
.github/workflows/compose_test.yaml

Removes a custom step which could be easier implemented by actions/checkout

Simplify action to checkout to docs

---

.github/actions/mkdocs-pages/action.yaml
.github/workflows/compose_test.yaml
.github/workflows/mkdocs.yaml

This fixes the documentation not processing nested readmes

Limit to docs download when docs folder is present

---

README.md
entrypoints/setup_git.sh

This is to avoid unpredictable behaviours

Avoid stashing and checking out if volume is set

---

services/backend/services/v4/config/.jobs.env

Fixes [issue #418](https://github.com/SciCatProject/scicatlive/issues/418)
Adds admin to the DELETE_JOB_GROUP, such that the environment agrees with testing env. on github workflows of backend repo

Add aadmin to DELETE_JOB_GROUP in release-jobs branch for dev

---

services/backend/services/v4/config/.dev.env

depends [on upstream fix](https://github.com/SciCatProject/scicat-backend-next/pull/1885)

Add JOBS related env variables for tests

---

services/frontend/compose.base.yaml

Add a health check to the frontend container

fix: add healthcheck to the frontend

---

.github/.markdownlint.json
.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
.github/SECURITY.md
.github/workflows/compose_test.yaml
README.md
services/backend/README.md
services/backend/services/keycloak/README.md
services/backend/services/ldap/README.md
services/backend/services/mongodb/README.md
services/backend/services/v3/README.md
services/backend/services/v3/services/archivemock/README.md
services/backend/services/v4/README.md
services/frontend/README.md
services/jupyter/README.md
services/landingpage/README.md
services/oaipmh/README.md
services/proxy/README.md
services/searchapi/README.md

Checks that MD files are linted according to standard rules
* all MD files formated to follow standard linting rules

docs: lint markdown files
