docker-compose.yaml, seed_db/mongo_import.sh
Before: When seeding mongo, the container first loads the datasets and then
restarts mongo. This might cause problems, as during the restart the
connection from catamel to mongo can be established, resulting in an
error. Now: this solution loads the db once it is up, avoiding the restart
=> Fix intermittend connection error to mongo

docker-compose.yaml
Traefik has been changed to reflect that the routing for backend-next has changed from explorer to explorer-next
=> fix backend-next explorer route

docker-compose.yaml
This pull request fixes a one line issue within the docker-compose.yaml that prevents the user from accessing the swagger UI
=> swagger ui forwarding fix

docker-compose.yaml
Adds an archival mock up service that will mark datasets as archived when an archival job is requested for them. 
Fixes #22
=> add archival mock service

README.md, services/mongodb/README.md, services/mongodb/config/init.js, services/mongodb/docker-compose.yaml
=> Set seeded DB name by BE version

services/archivemock/docker-compose.yaml
Closes #121 
* The archive mock will now use the newly available image in the project repository
=> use docker image for archive mock

README.md, services/.empty.yaml, services/backend/.compose.dev.yaml, services/backend/.compose.ldap.yaml, services/backend/.compose.oidc.yaml, services/backend/services/v3/.compose.dev.yaml, services/backend/services/v3/.compose.jobs.yaml, services/backend/services/v3/services/archivemock/.compose.dev.yaml, services/backend/services/v4/.compose.dev.yaml, services/backend/services/v4/.compose.elastic.yaml, services/frontend/.compose.dev.yaml, services/searchapi/.compose.dev.yaml
=> Change empty override files to symlinks

services/backend/services/v3/entrypoints/merge_json.sh
The latest version (6.0.1) is not compatible. This will probably be fixed once node-jq realises the bug
=> Bind node-jq version to latest working

.github/mkdocs.yaml, .github/overrides/main.html, .github/workflows/mkdocs.yaml
This PR adds the version selector to docs:
It also adds a deprecation warning and redirect for old versions
It also hardly remove cache to avoid having the wrong deprecation warning for the latest version
see the example [here](https://scicatproject.github.io/scicatlive/)
=> Add mkdocs mike for versions

.github/workflows/mkdocs.yaml
As pushes on main could be after the latest release, the HTML docs should always mark main as "non latest released"
=> Avoid tagging main with latest

services/mongodb/README.md, services/mongodb/compose.yaml, services/mongodb/config/init.js, services/mongodb/config/init.sh
Otherwise syntaxes like {$date: ...} are misinterpreted
=> Use mongoimport to process json mongo types

services/frontend/compose.dev.yaml
Depending on the host resources, 3 retries (default) might not be enough
=> Increase FE DEV retries

services/backend/services/v4/compose.base.yaml, services/backend/services/v4/compose.dev.yaml, services/frontend/compose.base.yaml
As supported by this [v4 relase](https://github.com/SciCatProject/scicat-backend-next/pkgs/container/backend-next/302018549?tag=v4.6.6), merged in scicatlive by this [PR](https://github.com/SciCatProject/scicatlive/pull/353), the platform constraint is now unnecessary
Relates to #145
=> Remove platform constraints

services/backend/services/v4/config/.dev.env, services/mongodb/README.md, services/mongodb/compose.yaml, services/mongodb/config/init.sh
=> Seed DEV v4 DB

.env, .github/workflows/compose_test.yaml, .gitignore, README.md, entrypoints/bidirectional_backup.sh, services/backend/services/v3/services/archivemock/compose.dev.yaml, services/compose.dev.yaml
using `unison` the bbackup folder on the host and the workdir in the container are synchronized (both ways)
=> Add ENV var to control DEV workdir mount to host

entrypoints/add_chrome.sh, entrypoints/setup_git.sh, services/compose.dev.yaml
This allows missing packages on container recreation and avoids `npm run build` buisy resources problems
=> Install all depens in DEV and avoid binding dist

.github/renovate.json
Newer rabbitmq minor and new frontend major introduce breaking changes for V3. This PR tells renovate to open these PRs as drafts and adds a label to them
=> Open draft PRs for v3 breaking changes

services/backend/services/v3/README.md, services/backend/services/v3/config/config.local.js, services/mongodb/config/seed/PublishedData.json
The current example prefix is not valid.
> A DOI prefix always starts with '10.' and continues with a number (e.g. '10.1234' or '10.20865').
The `10.9999` prefix doesn't seem to be assigned so I think it is safe to use it as an example.
See: https://commons.datacite.org/?query=10.9999
=> Replace example DOI prefix by a valid one

services/landingpage/README.md, services/landingpage/config/config.json
Added landing page settings for `statusMessage` (introduced in https://github.com/SciCatProject/LandingPageServer/pull/394) and `contactEmail` (introduced in https://github.com/SciCatProject/LandingPageServer/pull/396) to `config.json` and updated README.
=> (landingpage) add config keys for status-banner and support-email

.github/renovate.json
configure renovate to follow semantic-release
PR title lint fails for renovate PRs
Should create PRs with a valid title, see  https://docs.renovatebot.com/semantic-commits/
=> fix: configure renovate to follow semantic-release

.github/changed_files.yaml, .github/markdownlint/.markdownlint-cli2.yaml, .github/markdownlint/.markdownlint-rule-structure.js, .github/markdownlint/.markdownlint.yaml, .github/workflows/compose_test.yaml, services/backend/README.md, services/backend/services/keycloak/README.md, services/backend/services/ldap/README.md, services/backend/services/mongodb/README.md, services/backend/services/v3/README.md, services/backend/services/v3/services/archivemock/README.md, services/backend/services/v4/README.md, services/jupyter/README.md, services/landingpage/README.md, services/oaipmh/README.md, services/proxy/README.md, services/searchapi/README.md
Sets custom markdownlint rules to enforce a standard structure to READMEs under the `service/` folder.
To have a consistent structure of services READMEs
- all READMEs now follow predefined structure
- script to check mandatory sections and order added
- changed files split into mds and docs (one for markdownlint and one for mkdocs)
=> docs: standardize structure of READMEs sections

.github/eslint.config.mjs, .github/markdownlint/.markdownlint-rule-structure.js
Make stricted js linting rules and apply to markdownlinting customrule
- stricted JS rule
- applied to .github/markdownlint/.markdownlint-rule-structure.js
=> chore: make stricted js linting rules

.github/markdownlint/.markdownlint-rule-structure.js, services/backend/README.md, services/backend/services/keycloak/README.md, services/backend/services/ldap/README.md, services/backend/services/mongodb/README.md, services/jupyter/README.md
Enforce 1st headings to link https docs. This is enforced by the customRule regex in markdwonlint
- add rule to enforce https link in READMEs title
- add link in READMEs where missing
=> docs: enforce 1st headings to link https docs
